# Generated by Django 3.2.9 on 2021-11-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='password',
        ),
    ]
