# Generated by Django 3.2 on 2022-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_company', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('plate_number', models.CharField(max_length=9)),
                ('seats', models.IntegerField(default=62)),
                ('fare', models.CharField(max_length=6, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Departure Time')),
                ('contact', models.IntegerField(default=254)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('id_number', models.IntegerField(unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
