# Generated by Django 3.2 on 2022-09-05 18:26

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220905_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 21, 26, 18, 133494)),
        ),
        migrations.AlterField(
            model_name='book',
            name='seat',
            field=jsonfield.fields.JSONField(default=2),
        ),
    ]
